### ISSUE TITLE
样式丢失

### ISSUE THREAD

**Issue by luo772435545** [antdv-community/antdv-nuxt-starter#2]
跑完 run-s gen:css generate:nuxt 后，样式已经引入为啥还是样式丢失

**Comment by Panyoujies** [comment]
https://bomaos.com/post/59  可以使用这个方法

**Comment by fskarmeta** [comment]
doesnt  currentlywork with `theme.darkAlgorithm ` , also styles for element like `h1` differ between ssr and client

**Comment by aibayanyu20** [comment]
> doesn't currently work with `theme.darkAlgorithm ` , also styles for element like `h1` differ between ssr and client

try now starter
