### ISSUE TITLE
Add token in theme config => SSR not working

### ISSUE THREAD

**Issue by vietanhbui** [antdv-community/antdv-nuxt-starter#3]
When I use the switch to change the dark/light theme and use Ant Design Vue's theme token, every time I reload the page it takes about 1 second before Ant Design's css doesn't work.
![image](https://github.com/antdv-community/antdv-nuxt-starter/assets/43196820/0267c392-92f0-4f80-9402-af51b8ce1245)

**Comment by vietanhbui** [comment]
Similarly, when I configure directly, it also doesn't work
![image](https://github.com/antdv-community/antdv-nuxt-starter/assets/43196820/8b18226d-de67-4e62-ba66-7df362930ff8)

**Comment by aibayanyu20** [comment]
This looks like antdv library bug

**Comment by aibayanyu20** [comment]
try it     "ant-design-vue": "npm:@antd-tiny-vue/test@^4.0.7"

**Comment by aibayanyu20** [comment]
https://github.com/vueComponent/ant-design-vue/pull/7180

**Comment by aibayanyu20** [comment]
update 4.0.8
